name: CI and Delivery

on:
    push:
        branches:
            - master

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest

        steps:
            - name: Repository checkout
              uses: actions/checkout@v2

            - name: Use NodeJS 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install dependencies
              run: npm ci

            - name: Test
              run: npm run test:ci
              env:
                  CI: true
                  GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

            # - name: E2E
            #   run: npm run e2e
            #   env:
            #       CI: true

            - name: Build
              run: npm run build:ci
              env:
                  GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

            - name: Archive build
              if: success()
              uses: actions/upload-artifact@v2
              with:
                  name: dist
                  path: dist
            - name: Archive code coverage result
              if: success()
              uses: actions/upload-artifact@v2
              with:
                  name: coverage
                  path: coverage
